#!/usr/bin/env sh
# -*- mode: python; coding: utf-8 -*-
''':'
# Find the "best" installed Python:
for ver in 3.14 3.13 3.12 3.11 3.10 3.9 3; do
  if command -v "python$ver" >/dev/null 2>&1; then
    exec "python$ver" "$0" "$@"
  fi
done
echo "Error: No suitable Python found." >&2
exit 1
':'''

import os
import sys
import shutil
import subprocess
import glob
import getpass
import yaml
import secrets, string

from pprint import pprint, pformat

from argparse import ArgumentParser
from pathlib import Path
from jinja2 import Template

if sys.version_info < (3, 9):
    sys.exit("Need Python ≥ 3.9")



progname = os.path.basename(sys.argv[0])
version  = "0.84.8"


opts   = {}
config = {}
stash  = {}



###########
def main():
###########
    global opts
    global config
    global stash


    get_options()

    if not os.path.exists('.cbiroot'):
        sys.exit("Must be called in the cbi root directory - exiting.")

    if opts['target'] == None:
        sys.exit("Subcommand required - exiting.")

    if opts['target'] == 'config':
        create_sample_config()


    stash['cbi_root']       = os.getcwd()
    stash['playbooks_path'] = os.path.join(stash['cbi_root'], 'lib/playbooks')


    local_env_file    = f"env-{os.uname().nodename.split('.', 1)[0]}.yml"
    standard_env_file = "env.yml"

    paths = [local_env_file, standard_env_file]

    p = next(filter(Path.exists, map(Path, paths)), None)
    if p is None:
        raise FileNotFoundError("No config file found - exiting.")

    stash['config_path'] = os.path.join(stash['cbi_root'], p)

    with p.open(encoding="utf-8") as yamlfile:
        config = yaml.load(yamlfile, Loader=yaml.FullLoader)

    # debug("config_path", stash['config_path'])
    debug("config", config)

    go(target=opts['target'])  # up, down, ...



##################
def get_options():
##################
    global opts

    parser = ArgumentParser()

    subparsers = parser.add_subparsers(dest='target')
    parser.add_argument('-d', '--debug', action='store_true',
                        dest='debug', help='output debug messages')


    # config subcommand
    parser_config = subparsers.add_parser('config', help='create sample config')
    parser_config.add_argument('-f', '--force', action='store_true',
                               dest='force', help='overwrite existing config')
    parser_config.add_argument('--environment', dest='environment',
                               choices=['k3s', 'docker'],
                               default='k3s',
                               help='set environment type')


    all_stages = 'pre,gen,main,post'

    # up subcommand
    parser_up = subparsers.add_parser('up', help='create and start app')
    parser_up.add_argument('app_path', help='path to app')
    parser_up.add_argument('--stage', dest='stage', default=all_stages,
                           help=f'{all_stages} selection')
    parser_up.add_argument('--task', dest='task', default="",
                           help=f'task name or substring')
    parser_up.add_argument('-e', dest='extra', action="append",
                           help='extra vars')

    # down subcommand
    parser_down = subparsers.add_parser('down', help='stop and remove app')
    parser_down.add_argument('app_path', help='path to app')
    parser_down.add_argument('--stage', dest='stage', default=all_stages,
                           help=f'{all_stages} selection')
    parser_down.add_argument('--volumes', action='store_true', dest='volumes',
                             help='remove all volumes/PVs '
                             '(Default action with K3s).')

    # start subcommand
    parser_start = subparsers.add_parser('start', help='start app')
    parser_start.add_argument('app_path', help='path to app')
    parser_start.add_argument('--stage', dest='stage', default=all_stages,
                           help=f'{all_stages} selection')

    # stop subcommand
    parser_stop = subparsers.add_parser('stop', help='stop app')
    parser_stop.add_argument('app_path', help='path to app')
    parser_stop.add_argument('--stage', dest='stage', default=all_stages,
                           help=f'{all_stages} selection')

    # restart subcommand
    parser_restart = subparsers.add_parser('restart', help='restart app')
    parser_restart.add_argument('app_path', help='path to app')
    parser_restart.add_argument('--stage', dest='stage', default=all_stages,
                                help=f'{all_stages} selection')

    args = parser.parse_args()
    opts = vars(args)

    debug("opts", opts)



###############
def go(target):
###############

    global stash
    global config

    if target == "restart":
        go(target="stop")
        go(target="start")
        return


    app_path = Path(opts['app_path']).resolve()


    if not (app_path.exists() and app_path.is_dir()):
        sys.exit(f"App directory does not exist: {opts['app_path']}")

    stash['app_path'] = app_path
    debug("app_path", app_path)

    # E.g. we have:
    # app_path          = /home/user1/cbi/docker/sample-httpd
    # stash['cbi_root'] = /home/user1/cbi

    app_relpath = os.path.relpath(app_path, stash['cbi_root'])
    app_path_list = app_relpath.strip("/").split("/")

    # Now we have app_path_list = ['docker', 'sample-httpd']

    stash['app_path_list'] = app_path_list

    stash['app_name'] = app_path_list[-1].removesuffix('.ext')
    # (eventually an extension.)

    debug("Stash", stash)


    check_permissions()


    stages = opts['stage'].split(',')

    pre_files  = []
    main_files = []
    post_files = []


    selectors = {
        'up':    'U',
        'down':  'D',
        'start': 'S',
        'stop':  'K', # Like the ancient SysV-init :-)
    }
    selector = selectors[target]


    os.chdir(stash['app_path'])

    if 'pre' in stages:
        pre_files = sorted(glob.glob(f'tasks/{selector}[0-9][0-9]pre*'))
        pre_files = [s for s in pre_files if opts['task'] in s]
    if 'main' in stages:
        main_files = sorted(glob.glob(f'tasks/{selector}[0-9][0-9]main*'))
        main_files = [s for s in main_files if opts['task'] in s]
    if 'post' in stages:
        post_files = sorted(glob.glob(f'tasks/{selector}[0-9][0-9]post*'))
        post_files = [s for s in post_files if opts['task'] in s]

    debug("pre_files", pre_files)
    debug("main_files", main_files)
    debug("post_files", post_files)


    if 'pre' in stages:
        for file in pre_files:
            ansible_runner(action='run_tasks', arg=file)


    if 'gen' in stages:
        if (os.path.isdir('blueprint') and
            os.path.isfile('blueprint/info.yml') and target == "up"):
            ansible_runner(action='generate_files')

    if 'main' in stages:
        if (environment_type() == "docker" and
            os.path.isfile('run/docker-compose.yml')):

            compose_cmd = "docker compose -f run/docker-compose.yml".split()


            if target == "up":
                p = subprocess.run(compose_cmd + ['up', '-d'])


            if target == "down":
                if opts['volumes']:
                    p = subprocess.run(compose_cmd + ['down', '-v'])
                else:
                    p = subprocess.run(compose_cmd + ['down'])

                if os.path.isdir('run'):
                    shutil.rmtree('run')


            if target == "start":
                p = subprocess.run(compose_cmd + ['start'])


            if target == "stop":
                p = subprocess.run(compose_cmd + ['stop'])


        if environment_type() == "k3s":
            manifest = None
            if os.path.isfile('run/manifest.yml'):
                manifest = 'run/manifest.yml'
            elif os.path.isdir('run/manifests'):
                manifest = 'run/manifests'

            if manifest != None:
                if target == "up":
                    p = subprocess.run(['kubectl', 'apply', '-f', manifest])
                if target == "down":
                    p = subprocess.run(['kubectl', 'delete', '-f', manifest])


        for file in main_files:
            ansible_runner(action='run_tasks', arg=file)


    if 'post' in stages:
        for file in post_files:
            ansible_runner(action='run_tasks', arg=file)






##########################################
def ansible_runner(action=None, arg=None):
##########################################
    global stash
    global config
    global opts

    debug("ansible_runner|action", action)
    debug("ansible_runner|arg", arg)


    app_path_list = {"app_path_list": stash['app_path_list']}

    cmd = [
        "ansible-playbook",
        "-i", "localhost,",
        "-c", "local",
        f"{stash['playbooks_path']}/{action}.yml",
        "-e", f"config_path={stash['config_path']}",
        "-e", f"app_name={stash['app_name']}",
        "-e", f"app_path={stash['app_path']}",
        "-e", f"{str(app_path_list)}",
    ]

    if 'extra' in opts and opts['extra'] != None:
        for extra_var_value in opts['extra']:
            cmd.extend(['-e', extra_var_value])

    if action == 'run_tasks':
        cmd += ["-e", f"task_file={arg}"]

    debug("cmd", cmd)

    ansible_env=dict(
        #ANSIBLE_DISPLAY_SKIPPED_HOSTS='false',
        ANSIBLE_CALLBACK_RESULT_FORMAT='yaml',
        ANSIBLE_PYTHON_INTERPRETER='auto_silent',
        ANSIBLE_GATHERING='smart',
        ANSIBLE_CACHE_PLUGIN='jsonfile',
        ANSIBLE_CACHE_PLUGIN_CONNECTION='~/.ansible/fact_cache',
        ANSIBLE_CACHE_PLUGIN_TIMEOUT='86400',
    )

    p = subprocess.run(
        cmd,
        env={
            **os.environ,
            **ansible_env
        }
    )

    if p.returncode != 0:
        sys.exit(f"Ansible exited with error code {p.returncode}.")




###########################
def create_sample_config():
###########################
    global opts

    if os.path.exists('env.yml') and not opts['force']:
        sys.exit("env.yml already exists; use --force to overwrite.")


    with open("lib/templates/env-main.yml.j2", "r", encoding="utf-8") as f:
        global_part = Template(f.read())

    alphabet = string.ascii_letters + string.digits  # a-zA-Z0-9
    salt = ''.join(secrets.choice(alphabet) for _ in range(30))

    global_part_rendered = global_part.render(
        domain="example.org",
        password_base64="U2VjcmV0LTEyMzQ=",
        salt=salt,
    )


    with open(f"lib/templates/env-{opts['environment']}.yml.j2", "r",
              encoding="utf-8") as f:
        environment_part = Template(f.read())

    environment_part_rendered = environment_part.render(
        domain="example.org",
    )

    with open('env.yml', 'w') as f:
        f.write(global_part_rendered
                + "\n\n"
                + environment_part_rendered
                + "\n")

    sys.exit(0)




########################
def check_permissions():
########################
    global config

    if not config['global']['require_root']:
        return True

    if hasattr(os, "geteuid") and os.geteuid() != 0:
        sys.exit(f"Insufficient permissions. Please run as superuser (sudo?).")


#######################
def environment_type():
#######################
    p = os.path.normpath(opts['app_path'])
    components = os.path.split(p)

    if 'docker' in components:
        return 'docker'
    if 'k3s' in components:
        return 'k3s'

    sys.exit("Cannot detect environment type (docker|k3s). Exiting.")


#####################
def debug(desc, var):
#####################
    global opts

    RESET     = "\033[0m"
    GRAY      = "\033[37m"
    TURQUOISE = "\033[36m"

    if opts['debug']:
        print(f"{GRAY}DEBUG| {desc}: {TURQUOISE}")
        print(f"{pformat(var)}{RESET}")




if __name__ == '__main__':
    main()
