---
- name: System-specific installation of docker-ce
  include_tasks: "include/setup-{{ansible_os_family}}.yml"

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Upload daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "log-driver": "json-file",
          "log-opts": {
              "max-size": "20m",
              "max-file": "5",
              "compress": "true"
          },

          "live-restore": {{app.live_restore}}
      }
  register: config

- name: Reload docker service if needed
  service:
    name: docker
    state: reloaded
  when: config is changed
