---
- name: Gather facts
  setup:

- set_fact:
    distname: "{{ ansible_distribution| lower| replace(' ', '_') }}"

- debug: msg="Using '{{distname}}' as internal distribution name."

- name: System-specific installation of docker-ce
  include_tasks: "include/setup-{{distname}}.yml"

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes
    
- name: Upload daemon.json
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
          "log-driver": "json-file",
          "log-opts": {
              "max-size": "20m",
              "max-file": "5",
              "compress": "true"
          },

          "live-restore": true
      }
  register: config

- name: Reload docker service if needed
  service:
    name: docker
    state: reloaded
  when: config is changed

