---
- name: Gather facts
  setup:

- set_fact:
    distname: "{{ ansible_distribution| lower| replace(' ', '_') }}"

- debug: msg="Using '{{distname}}' as internal distribution name."

- name: System-specific installation of docker-ce
  include_tasks: "include/setup-{{distname}}.yml"

