---
- name: Install required base packages
  package:
    name:
      - bash-completion
      - curl

- set_fact:
    settings:
      Debian:
        passlib_package_name: python3-passlib
      Suse:
        passlib_package_name: python311-passlib

- name: Install Python passlib module
  package:
    name: "{{settings[ansible_os_family].passlib_package_name}}"
  when: ansible_os_family != "RedHat"
