---
- name: Download installer script
  get_url:
    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
    dest: /tmp/lazydocker_install_update_linux.sh
    force: true
  register: get_url_task

  
- name: Execute installer script; install to /usr/local/bin
  command: bash {{get_url_task.dest}}
  environment:
    DIR: /usr/local/bin
  when: get_url_task is changed
