---
- name: Create proxy network
  # We don't use the docker_network module, because on some systems
  # we don't have the community.docker collection installed :-(
  command: "docker network create {{docker.infra.proxy_network}}"
  register: docker_cmd
  failed_when: docker_cmd.rc != 0 and not 'already exists' in docker_cmd.stderr
  when: "'infra' in docker" # should almost always be the case.
