---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install some prereqs
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg

- name: Import Dockers official GPG key
  get_url:
    url: https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg
    dest: /etc/apt/keyrings/docker-archive-keyring.asc

# - name: Add docker apt repo
#   apt_repository:
#     repo: >-
#       deb [signed-by=/etc/apt/keyrings/docker-archive-keyring.asc]
#       https://download.docker.com/linux/{{ansible_distribution|lower}}
#       {{ansible_lsb.codename}} stable
#     filename: docker-ce
#     state: present


- name: Add docker repo in new deb822 format
  copy:
    dest: /etc/apt/sources.list.d/docker-ce.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/{{ansible_distribution|lower}}/
      Suites: {{ansible_lsb.codename}}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker-archive-keyring.asc
  register: deb822_task


- name: Pin version
  copy:
    dest: /etc/apt/preferences.d/docker.pref
    content: |
      Package: docker-ce*
      Pin: version 5:{{app.version}}.*
      Pin-Priority: 1000
  when: "'version' in app"

- name: apt update
  apt:
    update_cache: yes
  when: deb822_task.changed

- name: Install Docker Engine and Compose+Buildx plugin
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - docker-buildx-plugin
