- name: Scale statefulsets to one
  kubernetes.core.k8s_scale:
    api_version: apps/v1
    kind: StatefulSet
    namespace: awx
    replicas: 1

- name: Scale deployments to one
  kubernetes.core.k8s_scale:
    api_version: v1
    kind: Deployment
    namespace: awx
    replicas: 1
    
