---
- name: Gather facts
  setup:

- name: Call k3s-uninstall.sh
  command: k3s-uninstall.sh
  ignore_errors: true

- name: Remove K3s files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/lib/rancher
    - /etc/rancher
    - /etc/bash_completion.d/kubectl

- name: Remove Helm files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /usr/local/bin/helm

- name: Remove Podman
  package:
    name: podman
    state: absent

- name: Remove Podman files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /etc/containers/registries.conf.d/gitea.example.org.conf
    - /var/lib/containers
