---
- name: Call k3s-uninstall.sh
  command: k3s-uninstall.sh

- name: Remove K3s files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/lib/rancher
    - /etc/rancher
    - ~/.kube
