---
- name: Call k3s-uninstall.sh
  command: k3s-uninstall.sh
  ignore_errors: true

- name: Remove K3s files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/lib/rancher
    - /etc/rancher
    - /etc/bash_completion.d/kubectl
    - ~/.kube/config
    
- name: Remove Helm files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /usr/local/bin/helm
    - /root/.cache/helm
    - /root/.config/helm
