---
- name: Setup K3s
  shell:
    cmd: >-
      curl -fsSL https://get.k3s.io | sh -s - server \
          --write-kubeconfig-mode 644

  environment:
    INSTALL_K3S_VERSION: "{{versions['k3s']}}"
  register: cmd

- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}


- name: Install Helm
  shell: "curl -fsSL https://raw.githubusercontent.com/\
          helm/helm/main/scripts/get-helm-3 | bash"
  register: cmd
  ignore_errors: true # Rocky 9 / sudo: No /usr/local/bin in PATH
  
- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}

- stat:
    path: /usr/local/bin/helm
  register: p
      
- fail:
    msg: Something is wrong with Helm installation.
  when: not (p.stat.exists and p.stat.executable)

      
- name: Install Python Kubernetes support
  package:
    name: python3-kubernetes
    state: latest
