---
- name: Setup K3s
  shell:
    cmd: >-
      curl -fsSL https://get.k3s.io | sh -s - server \
          --write-kubeconfig-mode 644
      #   --resolv-conf /etc/k3s-resolv.conf

  environment:
    INSTALL_K3S_VERSION: "{{versions['k3s']}}"
  register: cmd

- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}


- name: Install Helm
  shell: "curl -fsSL https://raw.githubusercontent.com/\
          helm/helm/main/scripts/get-helm-3 | bash"
  register: cmd

- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}

- name: Install Python Kubernetes support
  package:
    name: python3-kubernetes
    state: latest

# - name: Install ACL package
#   package:
#     name: acl
#     state: present
