---
- set_fact:
    install_cmd: "curl -fsSL https://get.k3s.io | sh -"

- name: Setup K3s
  shell: "curl -fsSL https://get.k3s.io | sh -"
  environment:
    INSTALL_K3S_VERSION: "{{versions['k3s']}}"
  register: cmd

- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}
