---
- name: Setup K3s stable
  shell:  "curl -fsSL https://get.k3s.io | sh -"
  environment:
    INSTALL_K3S_VERSION: "{{versions['k3s']['stable']}}"
  register: cmd
  when: version_style == 'stable'


- debug:
    msg: |
      {{cmd.stdout}}
      {{cmd.stderr}}
