---
- name: Gather facts
  setup:


- assert:
    that:
      - iface is defined and iface  != ""
      - iface in ansible_interfaces


- command: printenv PATH
  changed_when: false
  register: p

- assert:
    that:
      - "'/usr/local/bin' in p.stdout"
    fail_msg: |
      /usr/local/bin is not in your PATH. If you are using sudo,
      you most likely have to add it to the secure_path
      in /etc/sudoers.


- block:
  - command: "id {{user}}"
    ignore_errors: true
    register: id_cmd

  - assert:
      that: id_cmd is success
      fail_msg: "The user '{{user}}' does not seem to exist"

  when: user is defined


- name: Gather service facts
  service_facts:

- assert:
    that:
      ansible_facts['services']['firewalld.service']['state'] != "running"
    fail_msg: |
      The firewalld service is be active, which will interfere with K3s.
      Please disable it to proceed.
  when: ansible_facts['services']['firewalld.service'] is defined
