---
- name: Gather facts
  setup:

- name: Create Bash completion plugin dir
  file:
    path: /etc/bash_completion.d
    state: directory

- name: Create kubectl completions
  shell:
    cmd: "kubectl completion bash >/etc/bash_completion.d/kubectl"
    creates: /etc/bash_completion.d/kubectl

- name: Create ~root/.kube dir
  file:
    path: ~root/.kube
    state: directory
    mode: 0700

- name: Create symlinks to global kubeconfig (due to helm)
  file:
    state: link
    follow: false
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~root/.kube/config

- block:
  - name: Create unpriv user ~/.kube dir
    file:
      path: ~{{user}}/.kube
      state: directory
      mode: 0700
      owner: "{{user}}"
      group: "{{lookup('pipe', 'id -gn ' + user)}}"

  - name: Create symlinks to global kubeconfig (due to helm)
    file:
      state: link
      follow: false
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~{{user}}/.kube/config
      owner: "{{user}}"
      group: "{{lookup('pipe', 'id -gn ' + user)}}"
  when: user is defined
