---

- block:
    
  - pause:
      prompt: "Username of unprivileged K3s user"
    register: answer

  - set_fact:
      k3s_user: "{{answer.user_input}}"
    
  when: k3s_user is undefined


- name: Create Bash completion plugin dir
  file:
    path: /etc/bash_completion.d
    state: directory


- name: Create kubectl completions
  shell:
    cmd: "kubectl completion bash >/etc/bash_completion.d/kubectl"
    creates: /etc/bash_completion.d/kubectl


- name: Grant ACL read access to global kubeconfig file
  ansible.posix.acl:
    path: /etc/rancher/k3s/k3s.yaml
    entity: "{{k3s_user}}"
    etype: user
    permissions: r
    state: present
    
- name: Create ~/.kube dir
  file:
    path: ~{{item}}/.kube
    state: directory
    mode: 0700
    owner: "{{item}}"
    group: "{{lookup('pipe', 'id -gn ' + item)}}"
  with_items:
    - root
    - "{{k3s_user}}"

- name: Create symlinks to global kubeconfig (due to helm)
  file:
    state: link
    follow: false
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{item}}/.kube/config
    owner: "{{item}}"
    group: "{{lookup('pipe', 'id -gn ' + item)}}"
  with_items:
    - root
    - "{{k3s_user}}"
