- name: Apply coredns custom configmap
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('file', 'run/coredns-custom.yml') }}"
  register: app_resources
    
- name: Rollout restart deployment coredns
  shell:  kubectl -n kube-system rollout restart deployment coredns
  when: app_resources is changed
