# - name: Check if the interface is up
#   command: ip link show cni0
#   register: result
#   until: "'state UP' in result.stdout"
#   retries: 10

# - name: Gather facts
#   setup:

# - name: Get ip of K3s cni0 interface
#   set_fact:
#     cni0_ip: "{{ ansible_facts['cni0']['ipv4']['address'] }}"

# - name: Renew contents os /etc/k3s-resolv.conf
#   copy:
#     dest: /etc/k3s-resolv.conf
#     content: |
#       # This file is submitted to K3s.
#       nameserver {{cni0_ip}}
