- name: Gather facts
  setup:

- debug: var=ansible_facts
    
- name: Get ip of K3s cni0 interface
  set_fact:
    cni0_ip: "{{ ansible_facts['cni0']['ipv4']['address'] }}"

- name: Renew contents os /etc/k3s-resolv.conf
  copy:
    dest: /etc/k3s-resolv.conf
    content: |
      # This file is submitted to K3s.
      nameserver {{cni0_ip}}

  

