---
- name: Gather facts
  setup:

- assert:
    that:
      - iface is defined and iface  != ""
      - iface in ansible_interfaces


- command: printenv PATH
  changed_when: false
  register: p

- assert:
    that:
      - "'/usr/local/bin' in p.stdout"
    fail_msg: |
      /usr/local/bin is not in your PATH. If you are using sudo,
      you most likely have to add it to the secure_path
      in /etc/sudoers.


- assert:
    that:
      - lookup('pipe', 'getent passwd '+user)
    fail_msg: "The user '{{user}}' does not seem to exist"
  when: user is defined

      
- meta: end_play