- name: Gather facts
  setup:

# - set_fact:
#     server_ip: "{{ ansible_facts[iface]['ipv4']['address'] }}"

- name: Run a dig command
  shell: dig ansible.com | grep SERVER
  register: dig_cmd


- set_fact:
    primary_dns: >-
      {{-
        dig_cmd.stdout |
        regex_search('SERVER: ([0-9\\.]+)', '\1')
      }}

- name: Create k3s-resolv.conf
  copy:
    dest: /etc/k3s-resolv.conf
    content: |
      # This file will be submitted to K3s.
      nameserver {{primary_dns}}


- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present


    
- name: Create /etc/dnsmasq.conf
  copy:
    dest: /etc/dnsmasq.conf
    content: |
      domain-needed
      bogus-priv
      no-resolv

      interface=lo
      interface=cni0
      bind-dynamic

      server={{primary_dns}}

      address=/{{domain}}/{{server_ip}}
  register: copy_dnsmasqconf_task

- name: Restart service and enable start on boot
  service:
    name: dnsmasq
    state: restarted
    enabled: yes
  when: copy_dnsmasqconf_task is changed
