- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- command: ip -br a
  register: ip_cmd

- debug: var=ip_cmd.stdout_lines
    
- pause:
    prompt: "Primary interface of your system? Select one of the above"
  register: answer

    
- name: Create k3s-resolv.conf
  copy:
    dest: /etc/k3s-resolv.conf
    content: |
      nameserver: {{ ansible_facts[answer]['ipv4']['address'] }}