---
- name: Create needed configuration directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /etc/containers/registries.conf.d
    - /etc/rancher/k3s


- name: Configure Podman for insecure private Gitea registry
  copy:
    dest: /etc/containers/registries.conf.d/gitea.{{domain}}.conf
    content: |
      [[registry]]
      location = "gitea.{{domain}}"
      insecure = true


- name: Configure K3s for insecure private Gitea registry
  copy:
    dest: /etc/rancher/k3s/registries.yaml
    content: |
      mirrors:
        my-gitea-registry:
          endpoint:
            - "https://gitea.{{domain}}"

      configs:
        gitea.{{domain}}:
          tls:
            insecure_skip_verify: true
