---
- name: Install global default gitconfig
  copy:
    dest: /etc/gitconfig
    mode: 0644
    content: |
      [user]
          name = First User
          email = user1@example.org
      [color]
          ui = auto
      [diff]
          wsErrorHighlight = all
      [core]
          editor = vim
          pager = less -FRX
      [push]
          default = matching
      [pull]
          ff = only
      [credential]
          helper = cache --timeout=3600
      [http]
          # Don't use this in production!
          sslVerify = false
      [init]
          defaultBranch = main
