---
- set_fact:
    gitea_admin_cmd: "docker compose exec --user git app gitea admin"
    user_name: "{{app.user_name}}"
    
- name: Create admin user '{{app.user_name}}'
  command:
    chdir: "{{app_path}}/run"
    cmd: >-
      {{gitea_admin_cmd}} user create
      --username {{app.user_name}}
      --password {{global.password | b64decode}}
      --admin
      --email {{app.user_name}}@{{global.domain}}
  register: admin_cmd
  failed_when: admin_cmd.rc != 0 and not 'user already exists' in admin_cmd.stderr
