---
- name: Gather facts
  setup:
    gather_subset: [distribution]

- name: Install package jq
  package:
    name: jq

    
- set_fact:
    package: step-cli_amd64.deb
  when: ansible_os_family == "Debian"

- set_fact:
    package: step-cli_amd64.rpm
  when: ansible_os_family != "Debian"

  
- name: Download step-cli package
  get_url:
    url: https://dl.smallstep.com/cli/docs-cli-install/latest/{{package}}
    dest: /tmp/{{package}}

    
- name: Install package
  apt:
    deb: /tmp/{{package}}
  when: ansible_os_family == "Debian"

- name: Install package
  command:
    cmd: rpm -i /tmp/{{package}}
    creates: /usr/bin/step
  when: ansible_os_family != "Debian"
